os:
  - linux
jobs:
  include:
    - stage: test
      install:
        - yarn
      language: node_js
      node_js: '12'
      script:
        - yarn test:ci
      cache:
        yarn: true
    - stage: deploy
      language: node_js
      node_js: '12'
      services:
        - docker
      install:
        - docker pull vanbujm/purple-iot-worshop-balena:latest
      script:
        - ./deploy.sh
      cache:
        yarn: true
stages:
  #  - test
  - deploy
