jobs:
  include:
    - stage: test
      install:
        - yarn
      language: node_js
      node_js: '12'
      script:
        - yarn test:ci
      cache:
        yarn: true

    - stage: deploy
      language: minimal
      script:
        - ./deploy.sh
stages:
#  - test
  - deploy
