jobs:
  include:
    - stage: test
      install:
        - yarn
      language: node_js
      node_js: '12'
      script:
        - yarn test:ci
      cache:
        yarn: true

    - stage: deploy
      addons:
        hosts:
          - git.balena-cloud.com
      language: minimal
      script:
        - ./deploy.sh
stages:
  - test
  - name: deploy
    if: branch = master
