jobs:
  include:
    - stage: test
      install:
        - yarn
      language: node_js
      node_js: '12'
      script:
        - yarn test:ci
      cache:
        yarn: true
    - stage: deploy
      services:
        - docker
      install:
        - docker pull vanbujm/purple-iot-worshop-balena:latest
      language: minimal
      script:
        - ./deploy.sh
stages:
  - test
  - deploy
