FROM balenalib/raspberrypi3-debian-node

RUN install_packages yarn
RUN install_packages git
RUN install_packages ssh
RUN install_packages tar
RUN install_packages gzip

WORKDIR /usr/app

CMD ["/bin/bash"]